language: python
python:
  - "3.6"

# command to install dependencies
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest --cov=amalgama
  - poetry run mypy amalgama --ignore-missing-imports
after_success:
  - codecov