language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run pytest --cov=amalgama
  - pipenv run mypy amalgama
after_success:
  - codecov